/**
 * The PostgreSQL baseline must describe the same database as schema.prisma.
 *
 * The committed migration history is SQLite-only (PRAGMA table rebuilds, a
 * randomblob() backfill), so PostgreSQL deployments use a single generated
 * baseline instead. That baseline is only trustworthy if it stays in step
 * with the schema - and it is generated by a script, so a schema change that
 * nobody regenerates for is exactly the drift to catch.
 *
 * This is the Postgres counterpart of schemaMigrationParity.test.ts, which
 * already guards the SQLite side. Two real generator bugs were found by
 * comparing the two: inline `// comments` silently dropped fields, and @@map
 * was ignored so two models produced wrongly-named tables.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const API_ROOT = resolve(__dirname, '../../..');
const SCHEMA = resolve(API_ROOT, 'prisma/schema.prisma');
const BASELINE = resolve(
  API_ROOT,
  'prisma/migrations-postgres/00000000000000_baseline/migration.sql',
);

const SCALARS = new Set([
  'String', 'Int', 'Float', 'Boolean', 'DateTime', 'Json', 'Decimal', 'BigInt', 'Bytes',
]);

/** Prisma scalar -> the PostgreSQL type `prisma migrate` emits. */
const PG_TYPE: Record<string, string> = {
  String: 'TEXT',
  Int: 'INTEGER',
  Float: 'DOUBLE PRECISION',
  Boolean: 'BOOLEAN',
  DateTime: 'TIMESTAMP(3)',
  Json: 'JSONB',
  BigInt: 'BIGINT',
  Bytes: 'BYTEA',
};

export type ColumnSpec = { type: string; nullable: boolean };

/**
 * Every scalar column the schema declares, with its expected PostgreSQL type
 * and nullability, keyed by the real (possibly @@map'd) table name.
 *
 * Comparing NAMES alone is not enough: a column emitted as TEXT where the
 * schema says Int, or as nullable where the schema says required, passes a
 * name-only check and then fails at runtime against a real database.
 */
function schemaColumns(): Record<string, Record<string, ColumnSpec>> {
  const src = readFileSync(SCHEMA, 'utf8');
  const modelNames = new Set(
    [...src.matchAll(/^model\s+(\w+)\s*\{/gm)].map((m) => m[1]),
  );

  const out: Record<string, Record<string, ColumnSpec>> = {};
  for (const m of src.matchAll(/^model\s+(\w+)\s*\{([\s\S]*?)^\}/gm)) {
    const [, name, body] = m;
    const mapped = /@@map\("([^"]+)"\)/.exec(body);
    const table = mapped ? mapped[1] : name;

    const cols: Record<string, ColumnSpec> = {};
    for (const rawLine of body.split('\n')) {
      let line = rawLine.trim();
      if (!line || line.startsWith('//') || line.startsWith('@@')) continue;
      const c = line.indexOf('//');
      if (c !== -1) line = line.slice(0, c).trim();
      const at = line.indexOf('@');
      const head = (at === -1 ? line : line.slice(0, at)).trim();

      const f = /^(\w+)\s+([\w[\]?]+)$/.exec(head);
      if (!f) continue;
      const [, field, type] = f;
      if (type.endsWith('[]')) continue;
      const base = type.replace(/[?[\]]/g, '');
      if (modelNames.has(base)) continue;
      if (!PG_TYPE[base]) continue;
      cols[field] = { type: PG_TYPE[base], nullable: type.endsWith('?') };
    }
    out[table] = cols;
  }
  return out;
}

/** The same, read back out of the generated baseline SQL. */
function baselineColumns(): Record<string, Record<string, ColumnSpec>> {
  const sql = readFileSync(BASELINE, 'utf8');
  const out: Record<string, Record<string, ColumnSpec>> = {};
  for (const m of sql.matchAll(/CREATE TABLE "(\w+)" \(([\s\S]*?)\n\);/g)) {
    const [, table, body] = m;
    const cols: Record<string, ColumnSpec> = {};
    for (const line of body.split('\n')) {
      const c = /^\s*"(\w+)"\s+([A-Z][A-Z0-9 ()]*?)(?:\s+NOT NULL|\s+DEFAULT|,|$)/.exec(line);
      if (!c) continue;
      cols[c[1]] = { type: c[2].trim(), nullable: !line.includes('NOT NULL') };
    }
    out[table] = cols;
  }
  return out;
}

/** Scalar columns each model declares, keyed by its real (possibly @@map'd) table. */
function schemaTables(): Record<string, Set<string>> {
  const src = readFileSync(SCHEMA, 'utf8');
  const modelNames = new Set(
    [...src.matchAll(/^model\s+(\w+)\s*\{/gm)].map((m) => m[1]),
  );

  const out: Record<string, Set<string>> = {};
  for (const m of src.matchAll(/^model\s+(\w+)\s*\{([\s\S]*?)^\}/gm)) {
    const [, name, body] = m;
    const mapped = /@@map\("([^"]+)"\)/.exec(body);
    const table = mapped ? mapped[1] : name;

    const cols = new Set<string>();
    for (const rawLine of body.split('\n')) {
      let line = rawLine.trim();
      if (!line || line.startsWith('//') || line.startsWith('@@')) continue;
      // Inline comments must be stripped, or `type String // note` is missed.
      const c = line.indexOf('//');
      if (c !== -1) line = line.slice(0, c).trim();
      const at = line.indexOf('@');
      const head = (at === -1 ? line : line.slice(0, at)).trim();

      const f = /^(\w+)\s+([\w[\]?]+)$/.exec(head);
      if (!f) continue;
      const [, field, type] = f;
      if (type.endsWith('[]')) continue;                  // relation list
      const base = type.replace(/[?[\]]/g, '');
      if (modelNames.has(base)) continue;                 // relation object
      if (!SCALARS.has(base)) continue;
      cols.add(field);
    }
    out[table] = cols;
  }
  return out;
}

/** Tables and columns the baseline SQL creates. */
function baselineTables(): Record<string, Set<string>> {
  const sql = readFileSync(BASELINE, 'utf8');
  const out: Record<string, Set<string>> = {};
  for (const m of sql.matchAll(/CREATE TABLE "(\w+)" \(([\s\S]*?)\n\);/g)) {
    const [, table, body] = m;
    const cols = new Set<string>();
    for (const line of body.split('\n')) {
      const c = /^\s*"(\w+)"\s+[A-Z]/.exec(line);
      if (c) cols.add(c[1]);
    }
    out[table] = cols;
  }
  return out;
}

describe('PostgreSQL baseline matches schema.prisma', () => {
  const declared = schemaTables();
  const built = baselineTables();

  it('parses both sides', () => {
    expect(Object.keys(declared).length).toBeGreaterThan(70);
    expect(Object.keys(built).length).toBeGreaterThan(70);
  });

  it('creates a table for every model', () => {
    const missing = Object.keys(declared).filter((t) => !built[t]);
    expect(missing, `models with no CREATE TABLE:\n${missing.join('\n')}`).toEqual([]);
  });

  it('creates no table without a model', () => {
    const extra = Object.keys(built).filter((t) => !declared[t]);
    expect(extra, `tables with no model:\n${extra.join('\n')}`).toEqual([]);
  });

  it('creates every scalar column', () => {
    const problems: string[] = [];
    for (const [table, cols] of Object.entries(declared)) {
      if (!built[table]) continue;
      for (const col of cols) {
        if (!built[table].has(col)) problems.push(`${table}.${col} missing from baseline`);
      }
    }
    expect(problems, problems.join('\n')).toEqual([]);
  });

  it('creates no column the schema does not declare', () => {
    const problems: string[] = [];
    for (const [table, cols] of Object.entries(built)) {
      if (!declared[table]) continue;
      for (const col of cols) {
        if (!declared[table].has(col)) problems.push(`${table}.${col} not in schema`);
      }
    }
    expect(problems, problems.join('\n')).toEqual([]);
  });

  it('honours @@map for table names', () => {
    // Two models map to snake_case tables. Emitting the model name instead
    // would create tables the generated client never queries.
    expect(built).toHaveProperty('content_translation');
    expect(built).toHaveProperty('scheduled_job_lock');
    expect(built).not.toHaveProperty('ContentTranslation');
    expect(built).not.toHaveProperty('ScheduledJobLock');
  });

  it('uses PostgreSQL types, never SQLite ones', () => {
    // DATETIME/REAL are the SQLite spellings; shipping them would fail on
    // Postgres at migrate time.
    // Strip comment lines first: the header explains WHY the SQLite
    // constructs are absent, and matching prose would fail for the wrong
    // reason.
    const sql = readFileSync(BASELINE, 'utf8')
      .split('\n')
      .filter((l) => !l.trim().startsWith('--'))
      .join('\n');
    expect(sql).not.toMatch(/\bDATETIME\b/);
    expect(sql).not.toMatch(/"\w+"\s+REAL\b/);
    expect(sql).not.toMatch(/\bPRAGMA\b/);
    expect(sql).not.toMatch(/randomblob/);
    expect(sql).toMatch(/TIMESTAMP\(3\)/);
    expect(sql).toMatch(/DOUBLE PRECISION/);
  });

  it('declares the provider as postgresql in its own lock file', () => {
    const lock = readFileSync(
      resolve(API_ROOT, 'prisma/migrations-postgres/migration_lock.toml'),
      'utf8',
    );
    expect(lock).toMatch(/provider\s*=\s*"postgresql"/);
  });

  it('gives every column the right PostgreSQL type', () => {
    // A name-only comparison would pass with Float emitted as TEXT.
    const declaredCols = schemaColumns();
    const builtCols = baselineColumns();
    const problems: string[] = [];
    for (const [table, cols] of Object.entries(declaredCols)) {
      for (const [col, spec] of Object.entries(cols)) {
        const got = builtCols[table]?.[col];
        if (!got) continue;                       // covered by the column test
        if (got.type !== spec.type) {
          problems.push(`${table}.${col}: expected ${spec.type}, got ${got.type}`);
        }
      }
    }
    expect(problems, problems.join('\n')).toEqual([]);
  });

  it('matches the schema on nullability', () => {
    // A required column emitted as nullable lets bad rows in; a nullable one
    // emitted NOT NULL rejects writes the application considers valid.
    const declaredCols = schemaColumns();
    const builtCols = baselineColumns();
    const problems: string[] = [];
    for (const [table, cols] of Object.entries(declaredCols)) {
      for (const [col, spec] of Object.entries(cols)) {
        const got = builtCols[table]?.[col];
        if (!got) continue;
        if (got.nullable !== spec.nullable) {
          problems.push(
            `${table}.${col}: schema nullable=${spec.nullable}, baseline nullable=${got.nullable}`,
          );
        }
      }
    }
    expect(problems, problems.join('\n')).toEqual([]);
  });

  it('emits a foreign key for every relation that has one', () => {
    // A missing FK is invisible until orphaned rows appear in production.
    const src = readFileSync(SCHEMA, 'utf8');
    const wanted = [...src.matchAll(/@relation\([^)]*fields:\s*\[/g)].length;
    const sql = readFileSync(BASELINE, 'utf8');
    const got = [...sql.matchAll(/ADD CONSTRAINT "\w+_\w+_fkey"/g)].length;
    expect(got).toBe(wanted);
  });

  it('emits every declared index and unique constraint', () => {
    // Losing an index is a silent performance cliff; losing a unique
    // constraint is a correctness bug (duplicate coupon codes, two carts per
    // product, a second row for the same subscriber).
    const src = readFileSync(SCHEMA, 'utf8');
    const sql = readFileSync(BASELINE, 'utf8');

    const wantIdx = [...src.matchAll(/@@index\(\[/g)].length;
    const gotIdx = [...sql.matchAll(/^CREATE INDEX /gm)].length;
    expect(gotIdx).toBe(wantIdx);

    const composites = [...src.matchAll(/@@unique\(\[/g)].length;
    const fields = [...src.matchAll(/@unique\b/g)].length - composites;
    const gotUnique = [...sql.matchAll(/^CREATE UNIQUE INDEX /gm)].length;
    expect(gotUnique).toBe(composites + fields);
  });

  it('gives the distributed lock a primary key on name', () => {
    // tryAcquireLock relies on a single-row conditional updateMany being
    // atomic. Without the PK two API instances could both claim the lease and
    // run the same job - duplicate abandoned-cart emails, double purges.
    const sql = readFileSync(BASELINE, 'utf8');
    expect(sql).toMatch(/CONSTRAINT "scheduled_job_lock_pkey" PRIMARY KEY \("name"\)/);
  });

  it('leaves @updatedAt columns without a database default', () => {
    // Prisma sets @updatedAt client-side. A DB default here would mask a
    // client that failed to send it, and diverge from what `prisma migrate`
    // generates - which `migrate diff` in the entrypoint would then flag as
    // drift on every boot.
    const sql = readFileSync(BASELINE, 'utf8');
    expect(sql).not.toMatch(/"updatedAt" TIMESTAMP\(3\) NOT NULL DEFAULT/);
    expect(sql).toMatch(/"updatedAt" TIMESTAMP\(3\) NOT NULL/);
  });

  it('keeps every identifier within PostgreSQL\'s 63-byte limit', () => {
    // PostgreSQL silently TRUNCATES identifiers at 63 bytes. Two constraint
    // names that collide once truncated make the migration fail partway
    // through, leaving a half-created database.
    const sql = readFileSync(BASELINE, 'utf8');
    const names = [
      ...[...sql.matchAll(/CONSTRAINT "([^"]+)"/g)].map((m) => m[1]),
      ...[...sql.matchAll(/CREATE (?:UNIQUE )?INDEX "([^"]+)"/g)].map((m) => m[1]),
    ];
    expect(names.length).toBeGreaterThan(300);

    const tooLong = names.filter((n) => n.length > 63);
    expect(tooLong, `over 63 bytes:\n${tooLong.join('\n')}`).toEqual([]);

    const byPrefix = new Map<string, Set<string>>();
    for (const n of names) {
      const k = n.slice(0, 63);
      if (!byPrefix.has(k)) byPrefix.set(k, new Set());
      byPrefix.get(k)!.add(n);
    }
    const collisions = [...byPrefix.entries()].filter(([, v]) => v.size > 1);
    expect(collisions.map(([k]) => k), 'identifiers collide when truncated').toEqual([]);
  });

  it('quotes identifiers that are PostgreSQL reserved words', () => {
    // "User" and "Order" are reserved. Unquoted they are a syntax error, and
    // this schema uses both as table names.
    const sql = readFileSync(BASELINE, 'utf8');
    for (const word of ['User', 'Order']) {
      expect(sql).toMatch(new RegExp(`CREATE TABLE "${word}"`));
      // No bare CREATE TABLE User / ALTER TABLE Order anywhere.
      expect(sql).not.toMatch(new RegExp(`(CREATE|ALTER) TABLE ${word}\\b`));
    }
  });

  it('pins the columns from the most recent schema work', () => {
    // Regression guard: these were added late and are the likeliest to be
    // missed by a stale baseline.
    expect(declared.Coupon).toContain('perCustomerLimit');
    expect(built.Coupon).toContain('perCustomerLimit');
    expect(built.Bundle).toContain('discountValue');
    expect(built.AbandonedCartEmail).toContain('recoveredAt');
    expect(built.NewsletterSubscriber).toContain('unsubscribeToken');
  });
});
