/**
 * The PostgreSQL baseline must describe the same database as schema.prisma.
 *
 * The committed migration history is SQLite-only (PRAGMA table rebuilds, a
 * randomblob() backfill), so PostgreSQL deployments use a single generated
 * baseline instead. That baseline is only trustworthy if it stays in step
 * with the schema - and it is generated by a script, so a schema change that
 * nobody regenerates for is exactly the drift to catch.
 *
 * This is the Postgres counterpart of schemaMigrationParity.test.ts, which
 * already guards the SQLite side. Two real generator bugs were found by
 * comparing the two: inline `// comments` silently dropped fields, and @@map
 * was ignored so two models produced wrongly-named tables.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const API_ROOT = resolve(__dirname, '../../..');
const SCHEMA = resolve(API_ROOT, 'prisma/schema.prisma');
const BASELINE = resolve(
  API_ROOT,
  'prisma/migrations-postgres/00000000000000_baseline/migration.sql',
);

const SCALARS = new Set([
  'String', 'Int', 'Float', 'Boolean', 'DateTime', 'Json', 'Decimal', 'BigInt', 'Bytes',
]);

/** Scalar columns each model declares, keyed by its real (possibly @@map'd) table. */
function schemaTables(): Record<string, Set<string>> {
  const src = readFileSync(SCHEMA, 'utf8');
  const modelNames = new Set(
    [...src.matchAll(/^model\s+(\w+)\s*\{/gm)].map((m) => m[1]),
  );

  const out: Record<string, Set<string>> = {};
  for (const m of src.matchAll(/^model\s+(\w+)\s*\{([\s\S]*?)^\}/gm)) {
    const [, name, body] = m;
    const mapped = /@@map\("([^"]+)"\)/.exec(body);
    const table = mapped ? mapped[1] : name;

    const cols = new Set<string>();
    for (const rawLine of body.split('\n')) {
      let line = rawLine.trim();
      if (!line || line.startsWith('//') || line.startsWith('@@')) continue;
      // Inline comments must be stripped, or `type String // note` is missed.
      const c = line.indexOf('//');
      if (c !== -1) line = line.slice(0, c).trim();
      const at = line.indexOf('@');
      const head = (at === -1 ? line : line.slice(0, at)).trim();

      const f = /^(\w+)\s+([\w[\]?]+)$/.exec(head);
      if (!f) continue;
      const [, field, type] = f;
      if (type.endsWith('[]')) continue;                  // relation list
      const base = type.replace(/[?[\]]/g, '');
      if (modelNames.has(base)) continue;                 // relation object
      if (!SCALARS.has(base)) continue;
      cols.add(field);
    }
    out[table] = cols;
  }
  return out;
}

/** Tables and columns the baseline SQL creates. */
function baselineTables(): Record<string, Set<string>> {
  const sql = readFileSync(BASELINE, 'utf8');
  const out: Record<string, Set<string>> = {};
  for (const m of sql.matchAll(/CREATE TABLE "(\w+)" \(([\s\S]*?)\n\);/g)) {
    const [, table, body] = m;
    const cols = new Set<string>();
    for (const line of body.split('\n')) {
      const c = /^\s*"(\w+)"\s+[A-Z]/.exec(line);
      if (c) cols.add(c[1]);
    }
    out[table] = cols;
  }
  return out;
}

describe('PostgreSQL baseline matches schema.prisma', () => {
  const declared = schemaTables();
  const built = baselineTables();

  it('parses both sides', () => {
    expect(Object.keys(declared).length).toBeGreaterThan(70);
    expect(Object.keys(built).length).toBeGreaterThan(70);
  });

  it('creates a table for every model', () => {
    const missing = Object.keys(declared).filter((t) => !built[t]);
    expect(missing, `models with no CREATE TABLE:\n${missing.join('\n')}`).toEqual([]);
  });

  it('creates no table without a model', () => {
    const extra = Object.keys(built).filter((t) => !declared[t]);
    expect(extra, `tables with no model:\n${extra.join('\n')}`).toEqual([]);
  });

  it('creates every scalar column', () => {
    const problems: string[] = [];
    for (const [table, cols] of Object.entries(declared)) {
      if (!built[table]) continue;
      for (const col of cols) {
        if (!built[table].has(col)) problems.push(`${table}.${col} missing from baseline`);
      }
    }
    expect(problems, problems.join('\n')).toEqual([]);
  });

  it('creates no column the schema does not declare', () => {
    const problems: string[] = [];
    for (const [table, cols] of Object.entries(built)) {
      if (!declared[table]) continue;
      for (const col of cols) {
        if (!declared[table].has(col)) problems.push(`${table}.${col} not in schema`);
      }
    }
    expect(problems, problems.join('\n')).toEqual([]);
  });

  it('honours @@map for table names', () => {
    // Two models map to snake_case tables. Emitting the model name instead
    // would create tables the generated client never queries.
    expect(built).toHaveProperty('content_translation');
    expect(built).toHaveProperty('scheduled_job_lock');
    expect(built).not.toHaveProperty('ContentTranslation');
    expect(built).not.toHaveProperty('ScheduledJobLock');
  });

  it('uses PostgreSQL types, never SQLite ones', () => {
    // DATETIME/REAL are the SQLite spellings; shipping them would fail on
    // Postgres at migrate time.
    // Strip comment lines first: the header explains WHY the SQLite
    // constructs are absent, and matching prose would fail for the wrong
    // reason.
    const sql = readFileSync(BASELINE, 'utf8')
      .split('\n')
      .filter((l) => !l.trim().startsWith('--'))
      .join('\n');
    expect(sql).not.toMatch(/\bDATETIME\b/);
    expect(sql).not.toMatch(/"\w+"\s+REAL\b/);
    expect(sql).not.toMatch(/\bPRAGMA\b/);
    expect(sql).not.toMatch(/randomblob/);
    expect(sql).toMatch(/TIMESTAMP\(3\)/);
    expect(sql).toMatch(/DOUBLE PRECISION/);
  });

  it('declares the provider as postgresql in its own lock file', () => {
    const lock = readFileSync(
      resolve(API_ROOT, 'prisma/migrations-postgres/migration_lock.toml'),
      'utf8',
    );
    expect(lock).toMatch(/provider\s*=\s*"postgresql"/);
  });

  it('pins the columns from the most recent schema work', () => {
    // Regression guard: these were added late and are the likeliest to be
    // missed by a stale baseline.
    expect(declared.Coupon).toContain('perCustomerLimit');
    expect(built.Coupon).toContain('perCustomerLimit');
    expect(built.Bundle).toContain('discountValue');
    expect(built.AbandonedCartEmail).toContain('recoveredAt');
    expect(built.NewsletterSubscriber).toContain('unsubscribeToken');
  });
});
